"use client";

import { useState, type KeyboardEvent, type ChangeEvent } from "react";
import { ArrowUp, Square, Paperclip } from "lucide-react";
import { cn } from "@/lib/utils";

export function MultimodalInput({
  onSend,
  onStop,
  isStreaming,
  placeholder,
}: {
  onSend: (text: string) => void;
  onStop?: () => void;
  isStreaming?: boolean;
  placeholder?: string;
}) {
  const [input, setInput] = useState("");

  const handleSend = () => {
    const text = input.trim();
    if (!text) return;
    onSend(text);
    setInput("");
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    setInput(e.target.value);
  };

  return (
    <div className="sticky bottom-0 z-10 bg-gradient-to-t from-background via-background to-transparent pt-6 pb-3 px-2">
      <div className="mx-auto max-w-4xl">
        <div className="flex items-end gap-2 rounded-[24px] border border-input bg-background/80 backdrop-blur-sm px-4 py-2 shadow-sm focus-within:ring-2 focus-within:ring-ring focus-within:border-ring transition-all">
          <button className="p-1.5 rounded-full text-muted-foreground hover:text-foreground hover:bg-accent transition-colors shrink-0">
            <Paperclip className="size-4" />
          </button>
          <textarea
            value={input}
            onChange={handleChange}
            onKeyDown={handleKeyDown}
            placeholder={placeholder || "Type a message..."}
            rows={1}
            className="flex-1 bg-transparent resize-none outline-none text-sm py-1.5 max-h-[200px] placeholder:text-muted-foreground"
            style={{ minHeight: "44px" }}
          />
          {isStreaming ? (
            <button
              onClick={onStop}
              className="p-2 rounded-full bg-foreground/10 text-foreground hover:bg-foreground/20 transition-colors shrink-0"
            >
              <Square className="size-4 fill-current" />
            </button>
          ) : (
            <button
              onClick={handleSend}
              disabled={!input.trim()}
              className={cn(
                "p-2 rounded-full transition-colors shrink-0",
                input.trim()
                  ? "bg-foreground text-background hover:bg-foreground/90"
                  : "bg-muted text-muted-foreground",
              )}
            >
              <ArrowUp className="size-4" />
            </button>
          )}
        </div>
        <p className="text-center text-xs text-muted-foreground mt-2">
          Responses are generated by AI agents. Always review important information.
        </p>
      </div>
    </div>
  );
}
